### ISSUE TITLE
Form data not submitting in Firefox

### ISSUE THREAD

**Issue by Arduinology** [rnicholus/ajax-form#34]
This is what my form tag looks like: 

``` html
<form method="POST" action="http://example.com" accept-charset="UTF-8" is="ajax-form" enctype="multipart/form-data">

</form>
```

Inside of the form tag I have a set of Polymer paper-input elements. After all is said and done this is what the input looks like:

``` html
    <input aria-label="Field" placeholder="Field" is="core-input" committedvalue="{{committedValue}}" on-change="{{ changeAction }}">
```

When I submit the form I am thrown a validation error. When I expose the GET Variables I see that in Firefox that not all form elements values are showing up.

**Comment by bnetanon** [comment]
has  there been a solution? same problem here.

**Comment by rnicholus** [comment]
I'm not aware of any issue. Firefox submissions are working without problems for me.
