### ISSUE TITLE
Create an awesome web page

### ISSUE THREAD

**Issue by rnicholus** [rnicholus/ajax-form#44]
...with code samples & demonstrations of the benefits of ajax-form.  If anyone is interested in helping out, please let me know.

**Comment by TheMallen** [comment]
I can probably help. Not this week though :)

**Comment by rnicholus** [comment]
Cool. I'm *way* overcommitted to projects outside of my day job as well at the moment, so no rush here.

**Comment by rnicholus** [comment]
Test e746c4367ebd8586ac47aece680288b6b8046d06

**Comment by jonbonraki** [comment]
Hi nicholous, 
is the ajax-form compatabile with 1.0,let me know i tried to look at dependencies and i haven't found any polymer 1.0 referneces, please let me know if i m missing something.

**Comment by rnicholus** [comment]
This is probably never going to happen because:

1. I've moved away from using web components and will likely only maintain this library when prompted by users.
2. I have a lot of other stuff going on.
