### ISSUE TITLE
ajax-form does not work with vulcanize

### ISSUE THREAD

**Issue by avivien-veolia** [rnicholus/ajax-form#50]
Hello,
I this polymer in my application, and as mentioned in the documentation, I put a `<form>` tag with is="ajax-form" in my page, like this:
```html
<form is="ajax-form" action="my/form/handler" method="post">
    <label>Enter your name: <input type="text" name="full_name"></label>
    ...
</form>
```
This works well with a non vulcanized code, but when I vulcanize my application it does not work anymore, the `<form is="ajax-form">` does not appear in the page.
If I put `<ajax-form>` instead of `<form is="ajax-form">` it works when I vulcanize my application, but it seems that the polymer element "ajax-form" is not fully functional when used in this way, some of my javascript code is broken.
Do you know where is the issue and how I can fix it ?
Thanks.

Regards,
Alexandre

**Comment by rnicholus** [comment]
Your ajax-form must extend the `HTMLFormElement`, so `is="ajax-form"` is required.

You'll probably want open up an issue in the vulcanize repo instead: https://github.com/Polymer/vulcanize/issues.
