### ISSUE TITLE
Does not work for Extended <file-input>

### ISSUE THREAD

**Issue by TheMallen** [rnicholus/ajax-form#51]
I was building an extension of <file-input> which parses and displays a file preview for each valid file. This does not work in the current implementation of `<ajax-form>` since the `maybeParseFileInput` function checks the tag name explicitly. This also means that `<ajax-form>` does not work with any alternate web component implementations of a file input.

I'm working on a pull request to fix this.

**Comment by rnicholus** [comment]
As long as your element exposes an input element with a type attribute of "file", there should be no issue. Otherwise, I'm not sure how you would identify such an element.

**Comment by TheMallen** [comment]
- If the input inherits from <file-input> the input element is hidden inside the shadow dom and doesn't seem to get parsed. 
- Since the `maybeParseFileInput` function checks for the tag name it doesn't get parsed their either. 
-  Since the `maybeParseGenericCustomElement` function only checks the value it also doesn't get parsed there...

Have tested this myself using an element which works in a native form.

**Comment by rnicholus** [comment]
Ajax-form checks for a file-input element, or any input element that has an attribute of type=file. Short of this, I'm not sure how you would identify such an element, short of some very specific convention.

**Comment by TheMallen** [comment]
Well, it is a 'very specific convention' itself to check specifically for `file-input`. I'd argue it's more general and makes more sense with Polymer's inheritance mechanisms to check if there is a `.files` attribute similar to how you check for a `value` attribute in the `genericCustomElement` parsing.

**Comment by rnicholus** [comment]
Yes, that particular convention is in place as I am also the developer of file-input. I suppose that convention could be removed and the custom element parser could be augmented to check for the `files` property.

**Comment by TheMallen** [comment]
Ok cool. That's what I was doing for the pull request. Glad you get my point :)

**Comment by rnicholus** [comment]
Yep, as long as an additional specific convention is not introduced, that should be fine.

**Comment by rnicholus** [comment]
Also, curious what your element's code looks like. I've done [quite a bit of work]http://fineuploader.com/) with the File API, scaling, previewing images, etc.

**Comment by TheMallen** [comment]
I'll be putting what I have so far up on webcomponents.io soon. Hadn't seen your link before, looks cool.

**Comment by rnicholus** [comment]
Released as part of 1.5.4.
