### ISSUE TITLE
ajax-form ignores paper checkbox

### ISSUE THREAD

**Issue by eximius313** [rnicholus/ajax-form#58]
Hi,
I have a very simple form containing one input and one paper-checkbox.
Although paper-checkbox has a name and an id, it is completely ignored by ajax-form.

When i do:
```javascript
form.addEventListener('submitting',
	    function(event) {
			var formData = event.detail.formData;
			if($('#agreement').attr('checked') !== undefined){
				formData.agreement = true;
			}
	    }
);
```
everything works fine.

Could you please fix it?
Thank you in advance

**Comment by rnicholus** [comment]
This would involving modifying the library to be aware of custom elements that are checkboxes, but do not extend `<input type="checkbox">`. I suppose the library could be modified to look at the `role` attribute to make this determination for custom elements.

**Comment by rnicholus** [comment]
This is now the last task to complete before releasing ajax-form 2.0.

**Comment by rnicholus** [comment]
Polymer seems to be a bit of a mess right now (one of the reasons why I stripped the dependence on Polymer out of ajax-form). Once it has stabilized a bit, I may consider looking into this again. I'll keep it open until that time comes.

**Comment by rnicholus** [comment]
Change of heart - I'll treat custom elements with a role of "checkbox" as standard checkboxes. If the paper-checkbox element does not behave like a typical checkbox (such as through its api) the polymer team will have to address this.

**Comment by eximius313** [comment]
But Polymer's paper-checkbox act as typical checkbox - it has a "checked" attribute

**Comment by rnicholus** [comment]
Great - then there won't be any issue with support for paper-checkbox. The changes will not explicitly support paper-checkbox. Instead, support will be for any element with a checkbox role that acts like a checkbox. If paper-checkbox changes in subsequent versions and no longer fits this model, then paper-checkbox support will fail as well.

**Comment by rnicholus** [comment]
This has been completed, and will be part of 2.0.
