### ISSUE TITLE
Ajax-form 2.0 causes 413 error

### ISSUE THREAD

**Issue by eximius313** [rnicholus/ajax-form#64]
I have a simple form:
```
<form action="/myForm" method="POST" is="ajax-form" id="myForm" enctype="multipart/form-data">
<file-input id="myInput" name="myInput" maxFiles="1" maxSize="1048576" minSize="1000" extensions='["jpg","jpeg","png","gif"]'>
Change				
</file-input>
<script>
document.getElementById('myInput').addEventListener("change", 
    function(event) {
        var validFiles = event.detail.valid;
        if(validFiles.length > 0){					
				document.querySelector('#myForm').submit();	
		}
    }
);
</script>
</form>
```
version 1.6.0 works great
When I upgrade to 2.0.0 I receive error:
```
POST http://localhost:9000/myForm     413 (Request Entity Too Large)    ajax-form.js:372
```
downgrading to 1.6.0 - works again

**Comment by eximius313** [comment]
Error happens even with files of the size of few KB

**Comment by rnicholus** [comment]
What does the request body look like? Are you choosing the same file in each case? A live example will be useful to reproduce as well, but these two questions are important to answer. Your server is rejecting the request due to size, so what are you seeing in terms of size differences? What is the expected size of the request?

**Comment by rnicholus** [comment]
Looks like <file-input> elements are not parsed at all in 2.0.0. see #65 for details. That doesn't explain a 413 though. If you are seeing that ajax-form is sending more info that necessary, let me know and I'll re-open.

**Comment by eximius313** [comment]
Of course I choose the same file.
It's size is just 3,73KB
My server is configured to handle even few MB, so 3KB file shouldn't be a problem
2.0.0 request:
```
Accept:*/*
Accept-Encoding:gzip, deflate
Accept-Language:pl-PL,pl;q=0.8,en-US;q=0.6,en;q=0.4
Connection:keep-alive
Content-Length:144
Content-Type:multipart/form-data
Cookie:JSESSIONID=XX; PLAY_SESSION=XX
Host:localhost:9000
Origin:http://localhost:9000
Referer:http://localhost:9000/myForm
User-Agent:XX

------WebKitFormBoundaryd9cF7TQPob9eALkB
Content-Disposition: form-data; name="xx"

undefined
------WebKitFormBoundaryd9cF7TQPob9eALkB--
```

1.6.0
```
Accept:*/*
Accept-Encoding:gzip, deflate
Accept-Language:pl-PL,pl;q=0.8,en-US;q=0.6,en;q=0.4
Connection:keep-alive
Content-Length:4003
Content-Type:multipart/form-data; boundary=----WebKitFormBoundaryaVp5cr9pzgmtynCn
Cookie:JSESSIONID=XX; PLAY_SESSION=XX
Host:localhost:9000
Origin:http://localhost:9000
Referer:http://localhost:9000/myForm
User-Agent:XX

------WebKitFormBoundaryaVp5cr9pzgmtynCn
Content-Disposition: form-data; name="xx"; filename="xx.jpg"
Content-Type: image/jpeg


------WebKitFormBoundaryaVp5cr9pzgmtynCn--
```

I can see that Content-Length is different even though it is the same file

**Comment by rnicholus** [comment]
If a smaller request results in a 413, thrn there is clearly some issue with your server. Most likely it is misreporting a failure to parse the file (since it is not sent) as a 413.

**Comment by eximius313** [comment]
Still doesn't work
The difference is in Content-Type header.
1.6.0
```
Content-Type:multipart/form-data; boundary=----WebKitFormBoundarymgbp0hBDB9DM5Hov
```
2.0.1
```
Content-Type:multipart/form-data
```

**Comment by rnicholus** [comment]
Fixed in 2.0.2. I inadvertently re-introduced code in 2.0.0. that explicitly specifies the Content-Type of a MPE, which is a no-no.

**Comment by eximius313** [comment]
now it works ;)
Thank you!
I hope that #63 will also be possible to fix.

**Comment by rnicholus** [comment]
The requests is being sent correctly, as far as I can tell. So that suggests the issue is with your server. If you can prove otherwise, I'll reopen.
