### ISSUE TITLE
<file-input> elements values are ignored during form field parsing

### ISSUE THREAD

**Issue by rnicholus** [rnicholus/ajax-form#65]
Caused by [a last minute change in custom element value parsing during 2.0.0 work](https://github.com/rnicholus/ajax-form/blob/2.0.0/ajax-form.js#L116). 

The field is sent to the server with a value of "undefined".

This will be fixed as part of 2.0.1.

**Comment by rnicholus** [comment]
To fix: custom-element parsing should include a check for a `files` property, or a `files` property should be checked regardless.

**Comment by eximius313** [comment]
when do you release 2.0.1? 
I could check if it works

**Comment by rnicholus** [comment]
As soon as time allows. I'll try to get a push fixed out tonight, assuming I can quickly fix, and have time to write a useful unit test.

**Comment by rnicholus** [comment]
Also noticed that empty file input fields are not being accounted for properly in MPE requests.

**Comment by rnicholus** [comment]
This has been fixed as part of 2.0.1, just released and on npm/bower.
