### ISSUE TITLE
Ajax form 2.0.2 ignores tinyMCE

### ISSUE THREAD

**Issue by eximius313** [rnicholus/ajax-form#67]
I have a tinyMCE textarea
```
<script type="text/javascript" src="/js/tinymce.min.js"></script>
    <script type="text/javascript">
		function tinyInit(){
	    	tinymce.init({
	            language : 'pl',
	            mode : "textareas",
	            plugins : "paste",
	            paste_word_valid_elements: "b,strong,i,em,h1,h2,h3,h4,h5,h6,ul,ol,li,br,p",
	            paste_retain_style_properties: "color"
	            paste_data_images: false,
	            editor_selector : "mceEditor",
	            menubar : false,
	            statusbar : false,
	            toolbar: " bold | italic | underline | bullist | numlist | undo | redo | formatselect | pastetext | pasteword "
	        });
		}
    	tinyInit();
    </script>
<form action="/myForm" method="POST" is="ajax-form">
<textarea id="myArea" name="myArea" placeholder="content" class="mceEditor"></textarea>
</form>
```
Ajax-form 1.6.0 works while version 2.0.2 ignores it

**Comment by rnicholus** [comment]
I'm not sure how tinymce is relevant here. Whst happens if you remove tinymceand try to submit a textarea with some content?

**Comment by eximius313** [comment]
Both works with regular textarea.

**Comment by rnicholus** [comment]
Ok. I'm not about to test with tinymce as I have no knowledge of that plugin. Once you figure out what is causing the issue for you, feel free to open up a pull request or an issue with the details.

**Comment by eximius313** [comment]
@rnicholus, here you have Ajax-form 2.1 and TinyMce: http://test.lepszapraca.com/test

As you can see - if you type something and hit "submit" the contents of the:
 ```<textarea id="test" name="test" placeholder="Test" class="mceEditor" aria-hidden="true" style="display: none;"></textarea>``` 
are not taken to the request.
Exactly same code is working well in Ajax-form 1.6.0

Could you please look and it?
Please

**Comment by eximius313** [comment]
let me know if you would like to see how 1.6.0 behaves - I have to switch branches

**Comment by rnicholus** [comment]
This library is not very complex, and since you are so well versed in
TinyMce, how about you create a pull request with the fix, or at least do a
little debugging and let me know exactly where the problem lies? Let's
remember that you haven't purchased anything from me, this library is open
source, and it's MIT licensed.

**Comment by eximius313** [comment]
I have investigated a bit and this is weird...
printing:
```
console.log(formElements);
```

Both here: https://github.com/rnicholus/ajax-form/blob/b9ffae5ad235300fe5e2056d6144ce5c974f2a81/ajax-form.js#L129 and https://github.com/rnicholus/ajax-form/blob/master/ajax-form.js#L199
gives the same result: an array of Objects, and each one has ```value``` property set correctly:
```
value: "<p>test</p>"
```
BUT when you try to print:
```
console.log(formElement.value);
```
in the lines: https://github.com/rnicholus/ajax-form/blob/b9ffae5ad235300fe5e2056d6144ce5c974f2a81/ajax-form.js#L133 and  https://github.com/rnicholus/ajax-form/blob/master/ajax-form.js#L123 
for the first one (1.6.0) you got:
```
<p>test</p>
``` 
but for the second (2.1.0) there is an empty line 
Do you have any idea why?

**Comment by eximius313** [comment]
Two differences I have spotted in ```formElements``` array:
1)in 2.1 baseURI is null:
![image](https://cloud.githubusercontent.com/assets/5578017/9837800/1e88bf1c-5a4b-11e5-9ee6-2de4825c62fb.png)
while in 1.6
is filled wich "action" value

2)in 2.1 "labels" is empty
![image](https://cloud.githubusercontent.com/assets/5578017/9837808/50d960c0-5a4b-11e5-882b-3a88431a203e.png)

while in 1.6 is:
![image](https://cloud.githubusercontent.com/assets/5578017/9837830/a2986ad2-5a4b-11e5-8ffe-676ec19b8438.png)

**Comment by eximius313** [comment]
And it happens in Google Chrome (Firefox seems to work)

**Comment by rnicholus** [comment]
All of the lines of code you have linked to are blank lines, so I'm not sure what you are referring to. I'm also having trouble understanding most of the comments you have posted. 

To get to the bottom of an issue, you must have two things:

1. A clearly identified problem.
2. A set of simple _specific_ steps needed to reproduce the issue. This includes actual input/output and expected input/output.

Once you are able to understand and articulate the above, it becomes much easier to solve the problem. So, if you are able to identify any issue with this code and explain how and why it should be adjusted to address a common and reasonable workflow, I will be happy to either make the change myself, or merge in a pull request.

**Comment by eximius313** [comment]
I'm referring to the blank lines, because  exactly in this lines I have put my ```console.log(variable)```

1)Ajax-form ingnores "value" of textarea enhanced by TinyMCE in Google Chrome
2)Steps to reproduce:
a)Enter to this site using **Firefox**: http://test.lepszapraca.com/test
b)Fill the field with any value ("test")
c)Click "submit"
d)Typed value is being passed to the server in Ajax request and hence stays in the field
e)Now Perform steps a,b,c with **Google Chrome**
f)Value is not being passed to the server and hence doesn't stays in the field which is an **error**.

If you put 
```
console.log(formElements);
```
in this exact line: https://github.com/rnicholus/ajax-form/blob/master/ajax-form.js#L199 you will see, that value is filled with proper data on both browsers

**Comment by rnicholus** [comment]
Ah, a live test site! Excellent. I'll take a look possibly this evening CST
when I get some free time.

**Comment by rnicholus** [comment]
I took a quick look. In Chrome, I entered some text into the editor, and then examined the value of all form fields in the document. I verified this by opening up dev tools in chrome and selecting all form fields. One way to do this is `document.querySelectorAll(':valid, :invalid')`. The form consisted of a couple submit buttons and one textarea:

```html
<textarea id="test" name="test" placeholder="Test" class="mceEditor" style="display: none;" aria-hidden="true"></textarea>
```

Even though the I entered text into the editor, the value of the textarea remained an empty string. I can't see how this is an ajax-form issue, since there is no data for ajax-form to submit. Instead, I would take a look at either your code or perhaps TinyMCE.

**Comment by eximius313** [comment]
Can you please try to submit the form using Firefox?
I have put console.log in lines 199 and 203 respectively to show you that output is exactly the same in both browsers (Firefox and Chrome).
When you expand ```formElements``` array in the console, you can observe that ```value``` field is filled correctly in both browsers, however in Firefox the "value" is being sent correctly. In Chrome "value" is being sent empty.
