### ISSUE TITLE
Got "Cannot read property 'addEventListener' of undefined"

### ISSUE THREAD

**Issue by emilhamep** [rnicholus/ajax-form#68]
I got rhe message Cannot read property 'addEventListener' of undefined". When try to implementing ajax-form. Like the images below:
![got can t read](https://cloud.githubusercontent.com/assets/12992413/8274056/b47eba20-18b1-11e5-8b19-071682e4b137.PNG)
And my javascript:
![my js in ajax-form](https://cloud.githubusercontent.com/assets/12992413/8274058/bf67627a-18b1-11e5-86f8-4551f2a8d016.PNG)
i also have imported ajax-form.html.
Why it can be happened?
Thanks in advance

**Comment by rnicholus** [comment]
This indicates that you have no form in your document.

**Comment by emilhamep** [comment]
I have form tag in my document,i copied from your demo code the tag form

**Comment by rnicholus** [comment]
Sorry, but if the browser complains that your "form" variable is undermined, given that the value is the result of an attempt to select form elements in your document, then there is no other possible cause that I am aware of.  I suggest you take a closer look at your document/markup.

**Comment by emilhamep** [comment]
Thanks for yours advices. I,m newbie using polymer and i want to
implementing ajax form for post data json. Do you have reference by your
own or the others?
I'm really appreciate your response & time

**Comment by rnicholus** [comment]
Ajax-form doesn't use or need polymer.

There is a live demo linked to from the documentation site. The markup can
be found at
https://github.com/rnicholus/ajax-form/tree/gh-pages/components/ajax-form/demo.html
.
