### ISSUE TITLE
Duplicate key/value pairs

### ISSUE THREAD

**Issue by TravisBurandt** [rnicholus/ajax-form#70]
I'm getting 2 of the same formData key/value pairs here...
https://github.com/rnicholus/ajax-form/blob/master/ajax-form.js#L271-L272

**Comment by rnicholus** [comment]
Please provide a markup and JavaScript needed to reproduce the issue, along with the specific values you used to reproduce.

**Comment by rnicholus** [comment]
Since I haven't heard back in 3 days, I'll have to assume this issue is resolved. If it is not, and you are able to provide markup and JS needed to reproduce (along w/ specific values required to reproduce), I'll be happy to re-open.
