### ISSUE TITLE
Polymer 0.5 dependency left in index.html

### ISSUE THREAD

**Issue by eximius313** [rnicholus/ajax-form#71]
After invoking ```bower install --save "ajax-form#^2.1"``` there is an ```ajax-form/index.html``` which contains references to the old Polymer:
```
  <script src="../webcomponentsjs/webcomponents.js"></script>
  <link rel="import" href="../polymer/polymer.html">
  <link rel="import" href="../core-component-page/core-component-page.html">
```

**Comment by rnicholus** [comment]
This is needed to render the documentation page. You will see that the library itself does not use polymer. I have no plans to upgrade the docs to use a later version of polymer or to not use polymer.

**Comment by eximius313** [comment]
But then, it is required by bower to have old polymer.
Could you please just change THREE lines?
1)this:
```
<script src="../webcomponentsjs/webcomponents.js"></script>
```
to this:
```
<script src="../webcomponentsjs/webcomponents-lite.js"></script>
```

2)this:
```
<link rel="import" href="../core-component-page/core-component-page.html">
```
to this:
```
<link rel="import" href="../iron-component-page/iron-component-page.html">
```
and
3)this:
```
<core-component-page></core-component-page>
```
to this:
```
<iron-component-page></iron-component-page>
```
?

**Comment by rnicholus** [comment]
How about you submit a pull request? This project is free and open source. Your other choice is to use npm instead. There is no real reason to use bower anymore if your dependencies are also on npm.

**Comment by eximius313** [comment]
OK, I have tried (my first pull request so far) ;)
Have I done it right?
