### ISSUE TITLE
DELETE method not available

### ISSUE THREAD

**Issue by flaiker** [rnicholus/ajax-form#75]
Hello,

any specific reason why method="delete" is not supported? I want to use this element to bind to a REST service, which by convention uses the delete-method on deletion-routes.

I saw patch was added at a later point as well ( #53 ) so I am wondering if it is just an oversight or if there is a technical reason.

**Comment by rnicholus** [comment]
Looks like this method support may have been lost in one of the more recent
major version updates. There is no unit test for this method either, which
is surprising. I'll gladly look at a pull request that re-introduces this
support, with at least one simple unit test.
