### ISSUE TITLE
NPM warning

### ISSUE THREAD

**Issue by bkr32** [rnicholus/ajax-form#77]
when trying to install using npm install ajax-form
i get the error 
C:\xampp\htdocs\ajax
└── ajax-form@2.1.2

npm WARN ENOENT ENOENT: no such file or directory, open 'C:\xampp\htdocs\ajax\package.json'
npm WARN EPACKAGEJSON ajax No description
npm WARN EPACKAGEJSON ajax No repository field.
npm WARN EPACKAGEJSON ajax No README data
npm WARN EPACKAGEJSON ajax No license field.

**Comment by rnicholus** [comment]
I don't see any errors. Sounds like some issues with your project's package.json.
