### ISSUE TITLE
Gradient has outdated direction syntax

### ISSUE THREAD

**Issue by eximius313** [rnicholus/ajax-form#81]
Autoprefixer throws such errors with your code:
[error] autoprefixer: /project/components/ajax-form/demo_resources/alertify.default.css:35:3: Gradient has outdated direction syntax. New syntax is like `to left` instead of `right`.
[error] autoprefixer: /project/components/ajax-form/demo_resources/alertify.default.css:44:3: Gradient has outdated direction syntax. New syntax is like `to left` instead of `right`.
[error] autoprefixer: /project/components/ajax-form/demo_resources/alertify.default.css:30:3: Gradient has outdated direction syntax. New syntax is like `to left` instead of `right`.
[error] autoprefixer: /project/components/ajax-form/demo_resources/alertify.default.css:36:3: Gradient has outdated direction syntax. New syntax is like `to left` instead of `right`.

**Comment by rnicholus** [comment]
I have no idea what any of this means. Can you explain?

**Comment by eximius313** [comment]
In means that lines 30, 35, 36 and 44 in the file ```alertify.default.css``` which you are using should be ```to top``` instead of ```top```

**Comment by eximius313** [comment]
This setting works fine:
```
	.alertify-button {
		border-radius: 4px;
		color: #FFF;
		font-weight: bold;
		padding: 6px 15px;
		text-decoration: none;
		text-shadow: 1px 1px 0 rgba(0,0,0,.5);
		box-shadow: inset 0 1px 0 0 rgba(255,255,255,.5);
		background-image: -webkit-linear-gradient(to top, rgba(255,255,255,.3), rgba(255,255,255,0));
		background-image:    -moz-linear-gradient(to top, rgba(255,255,255,.3), rgba(255,255,255,0));
		background-image:     -ms-linear-gradient(to top, rgba(255,255,255,.3), rgba(255,255,255,0));
		background-image:      -o-linear-gradient(to top, rgba(255,255,255,.3), rgba(255,255,255,0));
		background-image:         linear-gradient(to top, rgba(255,255,255,.3), rgba(255,255,255,0));
	}
	.alertify-button:hover,
	.alertify-button:focus {
		outline: none;
		background-image: -webkit-linear-gradient(to top, rgba(0,0,0,.1), rgba(0,0,0,0));
		background-image:    -moz-linear-gradient(to top, rgba(0,0,0,.1), rgba(0,0,0,0));
		background-image:     -ms-linear-gradient(to top, rgba(0,0,0,.1), rgba(0,0,0,0));
		background-image:      -o-linear-gradient(to top, rgba(0,0,0,.1), rgba(0,0,0,0));
		background-image:         linear-gradient(to top, rgba(0,0,0,.1), rgba(0,0,0,0));
	}
```

**Comment by rnicholus** [comment]
You'll want to post that issue in the alertify github repo then. This is the repo for ajax-form.

**Comment by eximius313** [comment]
Ok, I see than I'm not the only one with this problem: https://github.com/fabien-d/alertify.js/pull/253
Too bad that ```alertify.js``` is no longer maintained...
